insightsengineering/teal.gallery

inst/apps/exploratory/app.R

add dplyr prefix

---

inst/apps/exploratory/app.R

close #14 
I missed this in the previous PR

add ggextra

---

inst/apps/basic-teal/app.R
inst/apps/safety/app.R
tests/testthat/test-utils.R

following https://github.com/insightsengineering/teal.slice/pull/165

Refactor of the filter-panel

---

_internal/quarto/assets/style.scss
_internal/quarto/demo-template.ejs

Changes:
Adds a small note showcasing what the icon means in the demo page.

chore: add a note to show the meaning of icons in demo page

---

python/app.R

Fix unable to restore and run python app when the user has not set $PYTHON_PATH

---

longitudinal/app.R

Fixes #44 
It also replaces `filter` parameter  with `datanames`

Set up initial seed for `longitudinal` app for reproducibility

---

README.md
_internal/quarto/demo-apps.yml

Reorder the demo apps based on increasing complexity

---

longitudinal/app.R

Remove acronyms for example app code

---

.github/workflows/deploy.yaml

Disabling per https://github.com/insightsengineering/teal.gallery/pull/41#issuecomment-1728100099

Disable scheduled deployments for now

---

.github/workflows/deploy.yml

Not 100% sure about the directory path

Add safe directory

---

RNA-seq/app.R
basic-teal/app.R
early-dev/app.R
efficacy/app.R
exploratory/app.R
longitudinal/app.R
patient-profile/app.R
python/app.R
safety/app.R

Updates the teal.gallery apps to use the `build_app_title` helper function.
No need to worry about the renv.lock files as they will be auto-updated anyway.

Start to use `build_app_title` to create app title

---

patient-profile/app.R

Closes #128 
Related to changes in https://github.com/insightsengineering/teal.modules.clinical/pull/939

Replace parameter `aval` with `aval_var`

---

patient-profile/app.R

Closes #127 
Related to changes in https://github.com/insightsengineering/teal.modules.clinical/pull/940

Replace parameter `avalu` with `avalu_var`

---

safety/app.R

Closes #126 
Related to changes in https://github.com/insightsengineering/teal.modules.clinical/pull/941

Replace parameter `base_var` with `baseline_var`

---

.gitlab-ci.yml

To be merged after the respective MR in GitLab Shared Library is merged.

Add deployment pipeline definition

---

basic-teal/app.R

135 fix data in `nest_basic_teal` app

---

patient-profile/app.R

Capitalize Patient Profile app labels

---

RNA-seq/app.R
early-dev/app.R
efficacy/app.R
exploratory/app.R
longitudinal/app.R
patient-profile/app.R
safety/app.R

3 load specific scda data

---

README.md

Include the dev app deployments link in the readme

---

.github/workflows/docs.yaml

Fixes the [failed doc publish workflow](https://github.com/insightsengineering/teal.gallery/actions/runs/13162968516/job/36736129876)

Update upload-artifact action to v4

---

exploratory/app.R

Addressing the comment about the scatterplot matrix module label here:
https://github.com/insightsengineering/teal.modules.general/issues/63#issue-961829823

Update scatterplotmatrix label

---

longitudinal/app.R

Fixes https://github.com/insightsengineering/teal.gallery/issues/213
Related to https://github.com/insightsengineering/teal.goshawk/pull/360/files

set.seed in longitudinal app
